### ISSUE TITLE
PHP Fatal error:  Cannot redeclare class AppKernel

### ISSUE THREAD

**Issue by grimmlink** [liuggio/ExcelBundle#101]
After upgrading to symfony 2.8 i got this error on page execution:

> PHP Fatal error:  Cannot redeclare class AppKernel in /var/www/pw/m1/vendor/liuggio/ExcelBundle/Tests/app/AppKernel.php on line 0

Any idea ?

**Comment by liuggio** [comment]
so weird ....
no idea here

**Comment by liuggio** [comment]
@grimmlink  https://github.com/liuggio/ExcelBundle/blob/master/composer.json#L34 
should be fixed

**Comment by grimmlink** [comment]
thanks !

**Comment by webdevilopers** [comment]
Looks like this fix only available in `dev-master`? Guess it is too small for a major version release.
