### ISSUE TITLE
ClassNotFoundException

### ISSUE THREAD

**Issue by benblub** [liuggio/ExcelBundle#102]
Used Symfony 3.0

After install the Bundle via composer, 
`composer require liuggio/excelbundle`
Symfony throws error:

`ClassNotFoundException in app_dev.php line 27:
Attempted to load class "AppKernel" from the global namespace.
Did you forget a "use" statement for e.g. "Symfony\Bundle\FrameworkBundle\Tests\Functional\app\AppKernel" or "Symfony\Bundle\SecurityBundle\Tests\Functional\app\AppKernel"?`

composer.json was completly overwwritten, after rewrite and composer update Problem fixed.

**Comment by giorrrgio** [comment]
@benblub the error seems not related to this bundle. No issues here with symfony 3.0
