### ISSUE TITLE
Controller is not callable

### ISSUE THREAD

**Issue by rpostolov** [liuggio/ExcelBundle#103]
Hi,

I've installed this bundle but I have an error :
```
Controller "Ip\ReportBundle\Controller\ReportAdmin\ExcelController::excelAction" for URI "/admin/report/excel" is not callable
```
Can someone help me please ? I'm stuck.

Thanks a lot !

**Comment by rpostolov** [comment]
Hi !

Somebody to help ?

Maybe the creators of this bundle ?

**Comment by liuggio** [comment]
Hi @rpostolov this bundle doesn't have any route! 

I think you created a URL but not the controller :)

**Comment by arielcxl** [comment]
Hi @rpostolov, I think maybe you created the Controller and named the method "excelAction", as a convention when declaring the route that points to this action you don't need the "Action" word, your route should point only to "excel".

This is how routes in symphony work. Check this link [Symfony Routing](http://symfony.com/doc/current/book/routing.html)

**Comment by rpostolov** [comment]
Hi,

First of all, thank you for replies.

I installed this bundle and it created me an ExcelController in every bundle. Thats i think it's ok.

But the files 'ExcelControler.php' are empty. And i can't find what to do. Something is missing in that controler ? 

I'm using it with admingenerator. In fact i have a backgroffice usigne admingenerator, and i have a button to export the list of my item in an excel

Can i have some exemples of what i have to do please ?

Thanks a lot :)

**Comment by rpostolov** [comment]
Ps : this issue is not close.

**Comment by liuggio** [comment]
> Ps : this issue is not close.

Yes the issue is close, 
In this issues manager  we handle only issues related to ExcelBundle,
if you have problem with Symfony please ask in IRC symfony channel.

**Comment by rpostolov** [comment]
Come on, i just asked if ther is something to put in the Excelcontroller.php and if yes what to put.

And i don't know if it's symfony's error or your bundle because i don't know if the installation of Excelbundle is fully complete because you don't answer to my question...

So You want to close it, fine but why don't answer me ?

So please read again my post and if you don't mind answer me because this platform is for this no ?

Thanks again

**Comment by rpostolov** [comment]
Ok, tell me just if it's normall that my ExcelController.php, which is created in my bundle after installing, is empty ?

And if not what should it must contain ?

Thanks.

**Comment by liuggio** [comment]
Hi @rpostolov is so great to read what you write,
I'm fond of this.
Read the docs in the lazy dev section is all about you:

https://github.com/liuggio/ExcelBundle#for-lazy-devs

**Comment by rpostolov** [comment]
Thank's, you are welcome @liuggio 

It's a pleasure for us, users, to have people like you :)

Have a great day.

**Comment by sharjeelz** [comment]
Ethical Fight!
