### ISSUE TITLE
Deprecation since 3.3 and break at 4.0

### ISSUE THREAD

**Issue by ricohumme** [liuggio/ExcelBundle#129]
Hi,

Probably already know to you but didn't see it yet in the issues

```
Autowiring services based on the types they implement is deprecated since Symfony 3.3 and won't be supported in version 4.0. You should rename (or alias) the "phpexcel" service to "Liuggio\ExcelBundle\Factory" instead.
```

**Comment by adiq** [comment]
@ricohumme: the awesome guy @Jan0707 actually fixed this on SymfonyCon Cluj Hackday in ebd0f04eb0a2dd7b8a0c8c5cb18e45bdb9c3a05a + 598129aafb4bebb319407a435cec3323d47ffddf

We can just hope that @liuggio will consider moving this commit to master as soon as possible (as there are no BC breaks). A quick fix would be to just define this service and alias yourself, but that's more of a hack then real solution.

**Comment by doxt3r** [comment]
+1

**Comment by Jan0707** [comment]
> A quick fix would be to just define this service and alias yourself, but that's more of a hack then real solution.

I support this approach as an intermediate fix

**Comment by tinpansoul** [comment]
@liuggio, any news on this?

**Comment by adiq** [comment]
@TrogWarZ I think this library is not maintained anymore. Consider using new one as mentioned in https://github.com/liuggio/ExcelBundle/pull/125#issuecomment-359874868 ;-)

**Comment by ricohumme** [comment]
This is true. Composer shows this bundle has been abandoned. It recommends phpoffice/phpspreadsheet instead
