### ISSUE TITLE
No support for "createReader"

### ISSUE THREAD

**Issue by MicioBaus** [liuggio/ExcelBundle#82]
The function "createReader" of PHPExcel_IOFactory is not implemented in the bundle.
I find it very useful in order to create a csv file and convert it directly in other formats.

Regards

**Comment by liuggio** [comment]
Hi 
thanks for reporting do you like to add this feature, this project is community mantained,
and would be great if you can provide this,
if you are scared I'll help you through the process

let us know

**Comment by MicioBaus** [comment]
Created pull request. Hope everything is ok.

**Comment by vanclei** [comment]
is there any change this change be merged to master?

**Comment by vctls** [comment]
Referencing related pull request #83 for the record.
