### ISSUE TITLE
 Error: Call to a member function get() on null 500 Internal Server Error - FatalErrorException 

### ISSUE THREAD

**Issue by mobotan1** [liuggio/ExcelBundle#90]
I just spent whole day but unfortunately didn't find the solution - I have done all through the instruction, but every time I receive symfony debug error:
@mitsurugi Error: Call to a member function get() on null 500 Internal Server Error @        

My tests show that problem starts from declaration:
$phpExcelObject = $this->get('phpexcel')->createPHPExcelObject();

PHPExcel alone works finу via        //   $objPHPExcel = new PHPExcel();

Please, help - where to look, what to check?

**Comment by liuggio** [comment]
is the bundle installed?

https://github.com/liuggio/ExcelBundle#installation

**Comment by mobotan1** [comment]
Yes, sure.
I did update via composer and appkernel.php...

**Comment by liuggio** [comment]
where are you calling `$this`?

**Comment by liuggio** [comment]
BTW is not ExcelBundle related issue is how you configured test env.

**Comment by liuggio** [comment]
@mobotan1 if you publish some code would be possible help otherwise is not so easy.

**Comment by mobotan1** [comment]
Thanks in advance! I will post my code within 3 hours.

**Comment by mobotan1** [comment]
Here is my code cut

 

I have controller function:

 

/** @Route("/excel", name="ExcelJob")    */

public function ExcelAction() {

        $ExcelFile = "/home/my/project/1.xlsx”;

        $phpExcelObject =  $this->get(' ExcelService')-> LoadExcelFile($ExcelFile)

 

        //…

 

And I have separate class:

Services.yml

    ExcelService:

        class:        AppBundle\Controller\ExcelClass

        arguments:    

 

class ExcelClass extends Controller

{       

    public function LoadExcelFile($ExcelFile){

        $phpExcelObject = $this->get('phpexcel')->createPHPExcelObject($ExcelFile);

               

        return $phpExcelObject;

    }

**Comment by liuggio** [comment]
@mobotan1 

1. please use markdown
2. please remove the cc when reply from email
3. you have to inject the php excel into your class as collaborator $this not exist on your class `$this->get('phpexcel')`, you should ask on irc on any php channel.

**Comment by mobotan1** [comment]
I got it!
In controller - $phpExcelObject = $this->get('##Name_Of_Service##');

In Service - 
    protected $container;
    protected $phpexcel;
    
    public function setContainer (\Symfony\Component\DependencyInjection\ContainerInterface $container) {
        $this->container = $container;
        $this->phpexcel = $this->container->get('phpexcel');
    }
 public function ExcelTest(){
        $ExcelFile = // path to Excel file
        $phpExcelObject = $this->phpexcel->createPHPExcelObject($ExcelFile);
//...
}
