### ISSUE TITLE
Problem with save

### ISSUE THREAD

**Issue by titom59280** [liuggio/ExcelBundle#91]
Hello,

I tried to save a xls document in the folder C:windows\temp + some folder without success so far.

When I put a filename in parameter of the save function it works but when I tried to save the document in a specific path it does not work.

How can I handle this issue.

Thanks for your reply.

**Comment by liuggio** [comment]
I think you have a problem with the path name `C:windows\temp`? 
or check the permission :) 
can you paste che code maybe someone would help

**Comment by titom59280** [comment]
I have a variable named $documentToEdit with the path and the document name like this :
C:\Windows\TEMP/someUniqueFolder/Some document name.xls

then the code to save is this:
$writer->save($documentToEdit);

But with this I received the following error :
Warning: fopen(C:\Windows\TEMP/SomeUniqueFolder/Some document name.xls): failed to open stream: No such file or directory.

What I did and work so far is to write this :
$writer->save('test.xls);
who create and save a xls document in the web folder of my projet and then copy it with the filesystem of symfony in my unique folder on the temp folder of window and delete the test.xls document save with the $writer with the same filesystem.

**Comment by liuggio** [comment]
On windows you should use only "\" in the path

**Comment by titom59280** [comment]
i tried with only  "\" but the problem is still the same

**Comment by liuggio** [comment]
I closed this issue is not related to this bundle, the bundle is only a factory doesn't handle fs or path
I suggest to use the `sys_get_temp_dir`
