### ISSUE TITLE
make a copy of a sheet

### ISSUE THREAD

**Issue by titom59280** [liuggio/ExcelBundle#92]
Hello,

I have a excel template file with two sheets inside let say (Sheet 1 and Sheet 2) and I wanted to know if it is possible to create a Sheet 3 with the same content of Sheet 2).

I it is how can I do that?

Thanks for your reply

**Comment by liuggio** [comment]
HI I think you should ask this question to https://github.com/PHPOffice/PHPExcel library this is only a factory for sf2

**Comment by titom59280** [comment]
Ok I will thanks for your reply
