### ISSUE TITLE
add border

### ISSUE THREAD

**Issue by elgui02** [liuggio/ExcelBundle#97]
Hi everyone, i need add a border to the cells but i find a example:
"  $styleArray = array(
            'borders' => array(
                'allborders' => array(
                    'style' => 'PHPExcel_Style_Border::BORDER_THIN'
                )
            )
        );
" but on symfony i can't use this class " PHPExcel_Style_Border::BORDER_THIN " any ideas?

**Comment by liuggio** [comment]
Hi @elgui02 
can you provide the example you find?
are you sure this is symfony bundle-related?

**Comment by apachecoGrupeina** [comment]
$phpExcelObject->getActiveSheet()->getStyle('A8:L8')->getBorders()->getAllBorders()->setBorderStyle(\PHPExcel_Style_Border::BORDER_THIN);

This works for me.

**Comment by hectorh30** [comment]
From your code it seems your using the `PHPExcel_Style_Border::BORDER_THIN` constant as a string. Not sure if this is correct.

On the other hand, are you importing the class with a `use PHPExcel_Style_Border::BORDER_THIN`? In case you're not, try using the constant as `\PHPExcel_Style_Border::BORDER_THIN`.

**Comment by liuggio** [comment]
thanks @hectorh30 for replying 
... closing this is not a bundle related issue.

**Comment by rohitgarg111** [comment]
How can I use to align the text in merged columns , For example I merged a1:J1 then the text between is welcome , Now how to align welcome in center , Can you please send me the code or other way . 
Besides this , How to use borders as well . I used PHPExcel_Style_Border but error coming attemped to load class PHPExcel_Style_Border from namespace ?
