### ISSUE TITLE
New version for Symfony3

### ISSUE THREAD

**Issue by kachkaev** [liuggio/ExcelBundle#98]
Recent commits enable the bundle for Symfony3, but ```composer require liuggio/excelbundle``` still returns an error. Could you please tag the latest commit as v2.0.3 to fix this?

**Comment by czechnology** [comment]
+1

Thanks!

**Comment by liuggio** [comment]
@kachkaev would you like to provide this?

**Comment by kachkaev** [comment]
@liuggio I don't think there is anything here to propose as a new PR. The fix is just a matter of assigning tag ```v2.0.3``` to any commit later than ffacdb9d65b5dfb2623b481050aab5a977ca052a.

**Comment by liuggio** [comment]
@kachkaev  thanks a lot, done please let me know if the v2.0.3 is working as expected.

**Comment by czechnology** [comment]
Interestingly, it's tagged as version `v2.0.4` in [packagist](https://packagist.org/packages/liuggio/ExcelBundle#v2.0.4) but composer install works just as expected now, thanks!

**Comment by liuggio** [comment]
thanks @kachkaev  @czechnology
