### ISSUE TITLE
How can I merge two or multiple columns or rows?

### ISSUE THREAD

**Issue by RodolVelasco** [liuggio/ExcelBundle#99]
I cant find a way to merge columns or rows from the controller

**Comment by liuggio** [comment]
This is the documentation of the symfony bundle,
please can you refer to the php library doc. directly?

**Comment by RodolVelasco** [comment]
I found a solution:

$phpExcelObject->setActiveSheetIndex(0)->setCellValue('B2', 'TEST  TEST TEST TEST')->mergeCells('B2:F2');
